// <auto-generated />
using Calculator_Salar_WebApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Calculator_Salar_WebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Calculator_Salar_WebApp.Models.CalculatorSalariuBrut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("BazaImpozabila");

                    b.Property<long>("Cas");

                    b.Property<long>("Cass");

                    b.Property<long>("Impozit");

                    b.Property<long>("SalarBrut");

                    b.Property<long>("SalarNet");

                    b.HasKey("Id");

                    b.ToTable("CalculatorSalariuBrut");
                });

            modelBuilder.Entity("Calculator_Salar_WebApp.Models.CalculatorSalariuNet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("BazaImpozabila");

                    b.Property<long>("Cas");

                    b.Property<long>("Cass");

                    b.Property<long>("Impozit");

                    b.Property<long>("SalarBrut");

                    b.Property<long>("SalarNet");

                    b.HasKey("Id");

                    b.ToTable("CalculatorSalariuNet");
                });
#pragma warning restore 612, 618
        }
    }
}
